### ISSUE TITLE
[FR]: Add `netlify.toml` into template's root folder

### ISSUE THREAD

**Issue by andrey-jef** [ObsidianPublisher/template-netlify-vercel#1]
### Issue validator

- [X] My issue doesn't concern the [Obsidian Plugin](https://github.com/obsidianMkdocs/obsidian-github-publisher) (*[Make a feature request here](https://github.com/obsidianMkdocs/obsidian-github-publisher/issues/new?assignees=Mara-Li&labels=enhancement&template=request_form.yml&title=%5BFR%5D%3A+)*)
- [X] My issue doesn't concern the [Python Package](https://github.com/obsidianMkdocs/obsidian-mkdocs-publisher-python) (*[Make a feature request here](https://github.com/obsidianMkdocs/obsidian-mkdocs-publisher-python/issues/new?assignees=Mara-Li&labels=enhancement&template=feature_request.yml&title=%5BFR%5D%3A+)*)
- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate

### Is your feature related to a problem ?

Situation
- Currently, at this [documentation page](https://obsidian-publisher.netlify.app/getting%20started/publishing/) related to publishing, the end-user (like me) have to enter manually the parameters of `Basic build settings`.

Solution
- Add `netlify.toml` into repo's root folder to use the [File-based configuration](https://docs.netlify.com/configure-builds/file-based-configuration/)

What does it enhance?
- Convenience of end-user
    - don't need to enter manually the `Basic build settings`
- Simplicity of the documentation
    - in this [documentation page](https://obsidian-publisher.netlify.app/getting%20started/publishing/), you can remove the lines that guide user to input `build command` and `publish directory`

### What solution do you want to see ?

Add `netlify.toml` into repo's root folder to use the [File-based configuration](https://docs.netlify.com/configure-builds/file-based-configuration/)

```yaml
# netlify.toml
[build]
  command = "mkdocs build"
  publish = "site"
```

**Comment by Mara-Li** [comment]
thnaks :)
