### ISSUE TITLE
[Bug]: Python version problems with Netlify template - unable to build site

### ISSUE THREAD

**Issue by navhaxs** [ObsidianPublisher/template-netlify-vercel#3]
### Issue validation

- [X] My issue doesn't concern the [Obsidian Plugin](https://github.com/obsidianMkdocs/obsidian-github-publisher) (*[Make a bug report here](https://github.com/obsidianMkdocs/obsidian-github-publisher/issues/new?assignees=Mara-Li&labels=bug%2Ctriage&template=bug_report.yml&title=%5BBug%5D%3A+)*)
- [X] My issue doesn't concern the [Python Package](https://github.com/obsidianMkdocs/obsidian-mkdocs-publisher-python) (*[Make a bug report here](https://github.com/obsidianMkdocs/obsidian-mkdocs-publisher-python/issues/new?assignees=Mara-Li&labels=bug%2Ctriage&template=bug_report.yml&title=%5BBug%5D%3A+)*)
- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate

### Describe the bug

Hey there, I gave this a try but found that Netlify could not deploy the site out of the box.

```
ModuleNotFoundError: No module named 'obsidiantools'
```

I then tried adding obsidiantools from `requirements-actions.txt` to `requirements.txt`, but this didn't work since Netlify is stuck on 
Python version 3.8 (See https://docs.netlify.com/configure-builds/available-software-at-build-time/) and obsidiantools==0.10.0 requires at least 3.9, so this is broken on Netlify atm :/

Thought I'd let you know, this project looks really cool! :)

**Comment by makerjackie** [comment]
don't use obsidian tools on netlify or vercel because they only support python3.8

or

fire a FR / PR to obsidiantools github repo to support python3.8

**Comment by makerjackie** [comment]
sorry, my fault, vercel now use default python 3.9, so obsidian tools will work on vercel : https://vercel.com/docs/concepts/functions/serverless-functions/runtimes/python#python-version

**Comment by Mara-Li** [comment]
Thanks for the info!
