### ISSUE TITLE
Why set `<script> document.title = "{{ title }}" </script>` as default?

### ISSUE THREAD

**Issue by ooker777** [ObsidianPublisher/template-netlify-vercel#4]
In [line 62 of `overrides/partials/meta.html`](https://github.com/ObsidianPublisher/template-netlify-vercel/blame/3e775bce5676d1141052c082c336715737cea535/overrides/partials/meta.html#L62) you have: 
```html
<script> document.title = "{{ title }}" </script>
```
Why do you put it here as the default? I understand some may want to use that, but I think many people wouldn't think it's necessary. For instance, [it screws up Google Analytics tracking](https://github.com/squidfunk/mkdocs-material/discussions/6206#discussioncomment-7329818 "What set urls in lowercase and title not containing the site name? · squidfunk/mkdocs-material · Discussion #6206"): 

![](https://i.imgur.com/vH34kDM.png)

**Comment by Mara-Li** [comment]
Because they was a bug around it. If you want to edit your, go ahead. Don't forget to exclude it from auto-update.

Please, refrain to open issue for non relevant question. Use discussion instead.

**Comment by ooker777** [comment]
How to exclude it from auto-update? We can auto-update what?

Sorry. At first I thought this as a bug. I hope you don't feel annoying. You can delete this issue if necessary

**Comment by Mara-Li** [comment]
See https://github.com/ObsidianPublisher/actions
